spring.application.name=Movies catalog
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/movies_bd
spring.datasource.username=postgres
spring.datasource.password=72582480