spring.application.name=Movies catalog
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.datasource.url=jdbc:postgresql://localhost:5432/movies_db
spring.datasource.username=postgres
spring.datasource.password=72582480